### PR TITLE
Added GitHub workflow and GoReleaser

### PR DESCRIPTION
**Pull request by gaarutyunov**
Also you should change the name of the package. I left my username in it to test that everything works as expected.

1. In go.mod
2. In README.md
3. In main.go

### CODE REVIEW

**Comment by nitrocode** [comment]
@rpatrick00 @gaarutyunov why was the golang version downgraded from go1.18 to go1.17?

**Comment by gaarutyunov** [comment]
> @rpatrick00 @gaarutyunov why was the golang version downgraded from go1.18 to go1.17?

GitHub Actions didn't support go1.18. Maybe they do now, I should check.

**Comment by nitrocode** [comment]
goreleaser could be used and that supports all the modern golang versions 😄

**Comment by robertpatrick** [comment]
@nitrocode feel free to submit a PR to make the suggested change.  I am working on other, non-terraform related projects so I don't have time in the foreseeable future.

**Pull request merged**
